// Generated by gencpp from file roma_msgs/kalman_state.msg
// DO NOT EDIT!


#ifndef ROMA_MSGS_MESSAGE_KALMAN_STATE_H
#define ROMA_MSGS_MESSAGE_KALMAN_STATE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace roma_msgs
{
template <class ContainerAllocator>
struct kalman_state_
{
  typedef kalman_state_<ContainerAllocator> Type;

  kalman_state_()
    : latitude(0.0)
    , longitude(0.0)
    , velocity(0.0)
    , accel(0.0)
    , heading(0.0)
    , steer_ang(0.0)  {
    }
  kalman_state_(const ContainerAllocator& _alloc)
    : latitude(0.0)
    , longitude(0.0)
    , velocity(0.0)
    , accel(0.0)
    , heading(0.0)
    , steer_ang(0.0)  {
  (void)_alloc;
    }



   typedef double _latitude_type;
  _latitude_type latitude;

   typedef double _longitude_type;
  _longitude_type longitude;

   typedef double _velocity_type;
  _velocity_type velocity;

   typedef double _accel_type;
  _accel_type accel;

   typedef double _heading_type;
  _heading_type heading;

   typedef double _steer_ang_type;
  _steer_ang_type steer_ang;





  typedef boost::shared_ptr< ::roma_msgs::kalman_state_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::roma_msgs::kalman_state_<ContainerAllocator> const> ConstPtr;

}; // struct kalman_state_

typedef ::roma_msgs::kalman_state_<std::allocator<void> > kalman_state;

typedef boost::shared_ptr< ::roma_msgs::kalman_state > kalman_statePtr;
typedef boost::shared_ptr< ::roma_msgs::kalman_state const> kalman_stateConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::roma_msgs::kalman_state_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::roma_msgs::kalman_state_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace roma_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'roma_msgs': ['/home/trey/scr/robomagellan-2019/roma_ws/src/roma_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::roma_msgs::kalman_state_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::roma_msgs::kalman_state_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::roma_msgs::kalman_state_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::roma_msgs::kalman_state_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::roma_msgs::kalman_state_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::roma_msgs::kalman_state_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::roma_msgs::kalman_state_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c3db7ca6e3b082f234a4561fcd0ad615";
  }

  static const char* value(const ::roma_msgs::kalman_state_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc3db7ca6e3b082f2ULL;
  static const uint64_t static_value2 = 0x34a4561fcd0ad615ULL;
};

template<class ContainerAllocator>
struct DataType< ::roma_msgs::kalman_state_<ContainerAllocator> >
{
  static const char* value()
  {
    return "roma_msgs/kalman_state";
  }

  static const char* value(const ::roma_msgs::kalman_state_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::roma_msgs::kalman_state_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 latitude\n\
float64 longitude\n\
float64 velocity\n\
float64 accel\n\
float64 heading\n\
float64 steer_ang\n\
";
  }

  static const char* value(const ::roma_msgs::kalman_state_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::roma_msgs::kalman_state_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.latitude);
      stream.next(m.longitude);
      stream.next(m.velocity);
      stream.next(m.accel);
      stream.next(m.heading);
      stream.next(m.steer_ang);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct kalman_state_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::roma_msgs::kalman_state_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::roma_msgs::kalman_state_<ContainerAllocator>& v)
  {
    s << indent << "latitude: ";
    Printer<double>::stream(s, indent + "  ", v.latitude);
    s << indent << "longitude: ";
    Printer<double>::stream(s, indent + "  ", v.longitude);
    s << indent << "velocity: ";
    Printer<double>::stream(s, indent + "  ", v.velocity);
    s << indent << "accel: ";
    Printer<double>::stream(s, indent + "  ", v.accel);
    s << indent << "heading: ";
    Printer<double>::stream(s, indent + "  ", v.heading);
    s << indent << "steer_ang: ";
    Printer<double>::stream(s, indent + "  ", v.steer_ang);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROMA_MSGS_MESSAGE_KALMAN_STATE_H
