# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from roma_msgs/localization_data.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class localization_data(genpy.Message):
  _md5sum = "9e77329e7cd0c33db1d7f2019780b07a"
  _type = "roma_msgs/localization_data"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """float32 gps_lat
float32 gps_lon
float32 vel
float32 accel_x
float32 heading"""
  __slots__ = ['gps_lat','gps_lon','vel','accel_x','heading']
  _slot_types = ['float32','float32','float32','float32','float32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       gps_lat,gps_lon,vel,accel_x,heading

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(localization_data, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.gps_lat is None:
        self.gps_lat = 0.
      if self.gps_lon is None:
        self.gps_lon = 0.
      if self.vel is None:
        self.vel = 0.
      if self.accel_x is None:
        self.accel_x = 0.
      if self.heading is None:
        self.heading = 0.
    else:
      self.gps_lat = 0.
      self.gps_lon = 0.
      self.vel = 0.
      self.accel_x = 0.
      self.heading = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_5f().pack(_x.gps_lat, _x.gps_lon, _x.vel, _x.accel_x, _x.heading))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      _x = self
      start = end
      end += 20
      (_x.gps_lat, _x.gps_lon, _x.vel, _x.accel_x, _x.heading,) = _get_struct_5f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_5f().pack(_x.gps_lat, _x.gps_lon, _x.vel, _x.accel_x, _x.heading))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 20
      (_x.gps_lat, _x.gps_lon, _x.vel, _x.accel_x, _x.heading,) = _get_struct_5f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_5f = None
def _get_struct_5f():
    global _struct_5f
    if _struct_5f is None:
        _struct_5f = struct.Struct("<5f")
    return _struct_5f
